# Generated by Django 4.2.7 on 2025-01-22 13:12

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('shoes', 'Shoes'), ('bags', 'Bags'), ('tops', 'Tops'), ('dresses', 'Dresses'), ('skirts', 'Skirts'), ('jeans', 'Jeans'), ('accessories', 'Accessories'), ('jackets', 'Jackets'), ('activewear', 'Activewear'), ('underwear', 'Underwear'), ('lipstick', 'Lipstick')], default='shoes', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='c_name', unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='products/')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_description', models.TextField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=True, editable=False, null=True, populate_from='get_slug')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Charm_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charm_app.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
