# Generated by Django 5.1.5 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charm_app', '0006_purchasebill_salebill_stock_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='', upload_to='products/category/'),
        ),
    ]
