# Generated by Django 5.1.5 on 2025-02-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charm_app', '0007_remove_category_category_type_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
