# Generated by Django 5.1.5 on 2025-02-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charm_app', '0008_rename_img_product_img1_product_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
