# Generated by Django 5.1.5 on 2025-02-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charm_app', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
